# makefile for the energy model library

CC = g++
CFLAGS = -g 
#LIB = -lm -L/usr/lib -L../LE -lsimfold
LIB = -lm -L/usr/lib -L../LE -lsimfold
INC = -I./H -I./simfold
SRCS = Loop.cpp Stack.cpp Input.cpp Bands.cpp LoopList.cpp commonPK.cpp simfold/s_hairpin_loop.cpp simfold/s_internal_loop.cpp simfold/s_stacked_pair.cpp simfold/s_specific_functions.cpp simfold/s_energy_matrix.cpp simfold/s_multi_loop_sub.cpp simfold/s_multi_loop.cpp

OBJS = $(SRCS:.cpp=.o)

LIBOBJ = Loop.o Stack.o Input.o Bands.o LoopList.o commonPK.o s_hairpin_loop.o s_internal_loop.o s_stacked_pair.o s_specific_functions.o s_energy_matrix.o s_multi_loop_sub.o s_multi_loop.o

default: libLEModel.a 

$(PROG): $(OBJS)
	$(CC) -o $@ $(OBJS) $(LIB)

libLEModel.a: $(LIBOBJ)
	ar -rv libLEModel.a $(LIBOBJ)
	ranlib libLEModel.a
.SUFFIXES: .cpp
.cpp.o:
	$(CC) -c $(INC) $*.cpp $(CFLAGS)

clean:
	rm -f $(OBJS) $(PROG) libLEModel.a *~ core

depend:
	makedepend -- $(CFLAGS) -- $(SRCS)

# end of makefile
# DO NOT DELETE THIS LINE -- make depend depends on it.

commonPK.o: /usr/include/stdio.h /usr/include/features.h
commonPK.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
commonPK.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
commonPK.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
commonPK.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
commonPK.o: /usr/include/libio.h /usr/include/_G_config.h
commonPK.o: /usr/include/wchar.h /usr/include/bits/wchar.h
commonPK.o: /usr/include/gconv.h
commonPK.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stdarg.h
commonPK.o: /usr/include/bits/stdio_lim.h /usr/include/bits/sys_errlist.h
commonPK.o: /usr/include/stdlib.h /usr/include/math.h
commonPK.o: /usr/include/bits/huge_val.h /usr/include/bits/mathdef.h
commonPK.o: /usr/include/bits/mathcalls.h /usr/include/string.h
simfold/s_hairpin_loop.o: /usr/include/string.h /usr/include/features.h
simfold/s_hairpin_loop.o: /usr/include/sys/cdefs.h
simfold/s_hairpin_loop.o: /usr/include/bits/wordsize.h
simfold/s_hairpin_loop.o: /usr/include/gnu/stubs.h
simfold/s_hairpin_loop.o: /usr/include/gnu/stubs-32.h
simfold/s_hairpin_loop.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
simfold/s_hairpin_loop.o: /usr/include/ctype.h /usr/include/bits/types.h
simfold/s_hairpin_loop.o: /usr/include/bits/typesizes.h /usr/include/endian.h
simfold/s_hairpin_loop.o: /usr/include/bits/endian.h simfold/s_hairpin_loop.h
simfold/s_internal_loop.o: /usr/include/stdio.h /usr/include/features.h
simfold/s_internal_loop.o: /usr/include/sys/cdefs.h
simfold/s_internal_loop.o: /usr/include/bits/wordsize.h
simfold/s_internal_loop.o: /usr/include/gnu/stubs.h
simfold/s_internal_loop.o: /usr/include/gnu/stubs-32.h
simfold/s_internal_loop.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
simfold/s_internal_loop.o: /usr/include/bits/types.h
simfold/s_internal_loop.o: /usr/include/bits/typesizes.h /usr/include/libio.h
simfold/s_internal_loop.o: /usr/include/_G_config.h /usr/include/wchar.h
simfold/s_internal_loop.o: /usr/include/bits/wchar.h /usr/include/gconv.h
simfold/s_internal_loop.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stdarg.h
simfold/s_internal_loop.o: /usr/include/bits/stdio_lim.h
simfold/s_internal_loop.o: /usr/include/bits/sys_errlist.h
simfold/s_internal_loop.o: /usr/include/string.h /usr/include/stdlib.h
simfold/s_internal_loop.o: simfold/s_internal_loop.h
simfold/s_internal_loop.o: simfold/s_energy_matrix.h simfold/s_stacked_pair.h
simfold/s_internal_loop.o: simfold/s_hairpin_loop.h simfold/s_multi_loop.h
simfold/s_internal_loop.o: simfold/s_multi_loop_sub.h
simfold/s_stacked_pair.o: /usr/include/string.h /usr/include/features.h
simfold/s_stacked_pair.o: /usr/include/sys/cdefs.h
simfold/s_stacked_pair.o: /usr/include/bits/wordsize.h
simfold/s_stacked_pair.o: /usr/include/gnu/stubs.h
simfold/s_stacked_pair.o: /usr/include/gnu/stubs-32.h
simfold/s_stacked_pair.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
simfold/s_stacked_pair.o: simfold/s_stacked_pair.h simfold/s_energy_matrix.h
simfold/s_stacked_pair.o: simfold/s_hairpin_loop.h simfold/s_internal_loop.h
simfold/s_stacked_pair.o: simfold/s_multi_loop.h simfold/s_multi_loop_sub.h
simfold/s_specific_functions.o: /usr/include/stdio.h /usr/include/features.h
simfold/s_specific_functions.o: /usr/include/sys/cdefs.h
simfold/s_specific_functions.o: /usr/include/bits/wordsize.h
simfold/s_specific_functions.o: /usr/include/gnu/stubs.h
simfold/s_specific_functions.o: /usr/include/gnu/stubs-32.h
simfold/s_specific_functions.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
simfold/s_specific_functions.o: /usr/include/bits/types.h
simfold/s_specific_functions.o: /usr/include/bits/typesizes.h
simfold/s_specific_functions.o: /usr/include/libio.h /usr/include/_G_config.h
simfold/s_specific_functions.o: /usr/include/wchar.h
simfold/s_specific_functions.o: /usr/include/bits/wchar.h
simfold/s_specific_functions.o: /usr/include/gconv.h
simfold/s_specific_functions.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stdarg.h
simfold/s_specific_functions.o: /usr/include/bits/stdio_lim.h
simfold/s_specific_functions.o: /usr/include/bits/sys_errlist.h
simfold/s_specific_functions.o: /usr/include/stdlib.h /usr/include/math.h
simfold/s_specific_functions.o: /usr/include/bits/huge_val.h
simfold/s_specific_functions.o: /usr/include/bits/mathdef.h
simfold/s_specific_functions.o: /usr/include/bits/mathcalls.h
simfold/s_specific_functions.o: /usr/include/string.h
simfold/s_specific_functions.o: simfold/s_stacked_pair.h
simfold/s_specific_functions.o: simfold/s_energy_matrix.h
simfold/s_specific_functions.o: simfold/s_hairpin_loop.h
simfold/s_specific_functions.o: simfold/s_internal_loop.h
simfold/s_specific_functions.o: simfold/s_multi_loop.h
simfold/s_specific_functions.o: simfold/s_multi_loop_sub.h
simfold/s_specific_functions.o: simfold/s_specific_functions.h
simfold/s_energy_matrix.o: /usr/include/stdio.h /usr/include/features.h
simfold/s_energy_matrix.o: /usr/include/sys/cdefs.h
simfold/s_energy_matrix.o: /usr/include/bits/wordsize.h
simfold/s_energy_matrix.o: /usr/include/gnu/stubs.h
simfold/s_energy_matrix.o: /usr/include/gnu/stubs-32.h
simfold/s_energy_matrix.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
simfold/s_energy_matrix.o: /usr/include/bits/types.h
simfold/s_energy_matrix.o: /usr/include/bits/typesizes.h /usr/include/libio.h
simfold/s_energy_matrix.o: /usr/include/_G_config.h /usr/include/wchar.h
simfold/s_energy_matrix.o: /usr/include/bits/wchar.h /usr/include/gconv.h
simfold/s_energy_matrix.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stdarg.h
simfold/s_energy_matrix.o: /usr/include/bits/stdio_lim.h
simfold/s_energy_matrix.o: /usr/include/bits/sys_errlist.h
simfold/s_energy_matrix.o: /usr/include/string.h /usr/include/stdlib.h
simfold/s_energy_matrix.o: /usr/include/malloc.h simfold/s_energy_matrix.h
simfold/s_energy_matrix.o: simfold/s_stacked_pair.h simfold/s_hairpin_loop.h
simfold/s_energy_matrix.o: simfold/s_internal_loop.h simfold/s_multi_loop.h
simfold/s_energy_matrix.o: simfold/s_multi_loop_sub.h
simfold/s_multi_loop_sub.o: /usr/include/stdio.h /usr/include/features.h
simfold/s_multi_loop_sub.o: /usr/include/sys/cdefs.h
simfold/s_multi_loop_sub.o: /usr/include/bits/wordsize.h
simfold/s_multi_loop_sub.o: /usr/include/gnu/stubs.h
simfold/s_multi_loop_sub.o: /usr/include/gnu/stubs-32.h
simfold/s_multi_loop_sub.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
simfold/s_multi_loop_sub.o: /usr/include/bits/types.h
simfold/s_multi_loop_sub.o: /usr/include/bits/typesizes.h
simfold/s_multi_loop_sub.o: /usr/include/libio.h /usr/include/_G_config.h
simfold/s_multi_loop_sub.o: /usr/include/wchar.h /usr/include/bits/wchar.h
simfold/s_multi_loop_sub.o: /usr/include/gconv.h
simfold/s_multi_loop_sub.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stdarg.h
simfold/s_multi_loop_sub.o: /usr/include/bits/stdio_lim.h
simfold/s_multi_loop_sub.o: /usr/include/bits/sys_errlist.h
simfold/s_multi_loop_sub.o: /usr/include/malloc.h simfold/s_multi_loop_sub.h
simfold/s_multi_loop_sub.o: simfold/s_energy_matrix.h
simfold/s_multi_loop_sub.o: simfold/s_stacked_pair.h simfold/s_hairpin_loop.h
simfold/s_multi_loop_sub.o: simfold/s_internal_loop.h simfold/s_multi_loop.h
simfold/s_multi_loop.o: /usr/include/stdio.h /usr/include/features.h
simfold/s_multi_loop.o: /usr/include/sys/cdefs.h /usr/include/bits/wordsize.h
simfold/s_multi_loop.o: /usr/include/gnu/stubs.h /usr/include/gnu/stubs-32.h
simfold/s_multi_loop.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stddef.h
simfold/s_multi_loop.o: /usr/include/bits/types.h
simfold/s_multi_loop.o: /usr/include/bits/typesizes.h /usr/include/libio.h
simfold/s_multi_loop.o: /usr/include/_G_config.h /usr/include/wchar.h
simfold/s_multi_loop.o: /usr/include/bits/wchar.h /usr/include/gconv.h
simfold/s_multi_loop.o: /usr/lib/gcc/i586-suse-linux/4.1.0/include/stdarg.h
simfold/s_multi_loop.o: /usr/include/bits/stdio_lim.h
simfold/s_multi_loop.o: /usr/include/bits/sys_errlist.h /usr/include/malloc.h
simfold/s_multi_loop.o: simfold/s_multi_loop.h simfold/s_energy_matrix.h
simfold/s_multi_loop.o: simfold/s_stacked_pair.h simfold/s_hairpin_loop.h
simfold/s_multi_loop.o: simfold/s_internal_loop.h simfold/s_multi_loop_sub.h
